### ISSUE TITLE
[EXP]Gold seeding

### ISSUE THREAD

**Issue by Huijin-An** [Huijin-An/Huijin-An#4]
## What
soak TNC into gold solution- overnight
soak NC into gold solution- overnight
filtration NC

## Why
to compare and check which method is good for attaching gold to the PSiNPs surface. 

## TODO
- [ ] prepare gold solution
- [ ] prepare plasma treatment
- [ ] prepare the method of filtration
